config/routes.rb
Rails.application.routes.draw do

  resources :use_types
  resources :contact_methods
  resources :statuses
  devise_for :users

  resources :properties do
    resources :units
  end
  resources :garages
  resources :sources
  resources :prequalifications
  resources :representations
  resources :residential_applications
  resources :units do
    collection do
      get 'search'
    end
  end
  resources :brokers do
    collection do
      get 'search'
    end
  end
  resources :residential_leads do
    collection do
      get 'search'
    end
    resources :residential_applications
    resources :prequalifications
  end
  
  get 'pages/home'
  get 'pages/available_units'

  resources :commercial_leads do
    collection do
      get 'search'
      get :active
      get :application
      get :signed
      get :rented_elsewhere
      get :not_a_good_fit
      get :denied
      get :closed
    end
  end

  root 'pages#home'

end

app/models/commercial_lead.rb
class CommercialLead < ActiveRecord::Base

  has_many :unit_references
  has_many :units, :through => :unit_references
  has_many :suggested_units
  has_many :units, :through => :suggested_units
  belongs_to :source
  belongs_to :status
  belongs_to :contact_method
  belongs_to :broker
  belongs_to :use_type

  has_many :property
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR use ILIKE ? OR description ILIKE ? OR email ILIKE ? OR company_name ILIKE ? OR properties_referenced ILIKE ? OR properties_suggested ILIKE ? OR properties_shown ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |commercial_lead|
        csv << commercial_lead.attributes.values_at(*column_names)
      end
    end  
  end

end

app/controllers/commercial_leads_controller.rb
class CommercialLeadsController < ApplicationController
  before_action :set_commercial_lead, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /commercial_leads
  # GET /commercial_leads.json
  def search
    if params[:search].present?
        @commercial_leads = CommercialLead.search(params[:search])
    else
        @commercial_leads = CommercialLead.all.order('initial_contact DESC')
    end
  end

  def index
    @commercial_leads = CommercialLead.all.order('initial_contact DESC')

      respond_to do |format|
        format.html
        format.csv { render text: @commercial_leads.to_csv }
        format.xls { send_data @commercial_leads.to_csv(col_sep: "\t") }
      end
  end
  def active
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Active" }).order('initial_contact DESC')
    render action: :index
  end

  def application
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Application/Proposal" }).order('initial_contact DESC')
    render action: :index
  end

  def signed
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Signed" }).order('initial_contact DESC')
    render action: :index
  end

  def rented_elsewhere
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Rented Elsewhere" }).order('initial_contact DESC')
    render action: :index
  end

  def not_a_good_fit
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Not a Good Fit" }).order('initial_contact DESC')
    render action: :index
  end

  def denied
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Denied" }).order('initial_contact DESC')
    render action: :index
  end

  def closed
    @commercial_leads = CommercialLead.joins(:status).where(statuses: { 
      name: "Closed" }).order('initial_contact DESC')
    render action: :index
  end

  def send_email
  end
  # GET /commercial_leads/1
  # GET /commercial_leads/1.json
  def show
    @units = @commercial_lead.units
  end

  # GET /commercial_leads/new
  def new
    @commercial_lead = CommercialLead.new
  end

  # GET /commercial_leads/1/edit
  def edit
  end

  # POST /commercial_leads
  # POST /commercial_leads.json
  def create
    @commercial_lead = CommercialLead.new(commercial_lead_params)

    respond_to do |format|
      if @commercial_lead.save
        format.html { redirect_to @commercial_lead, notice: 'Commercial lead was successfully created.' }
        format.json { render :show, status: :created, location: @commercial_lead }
      else
        format.html { render :new }
        format.json { render json: @commercial_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commercial_leads/1
  # PATCH/PUT /commercial_leads/1.json
  def update
    respond_to do |format|
      if @commercial_lead.update(commercial_lead_params)
        format.html { redirect_to @commercial_lead, notice: 'Commercial lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @commercial_lead }
      else
        format.html { render :edit }
        format.json { render json: @commercial_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commercial_leads/1
  # DELETE /commercial_leads/1.json
  def destroy
    @commercial_lead.destroy
    respond_to do |format|
      format.html { redirect_to commercial_leads_url, notice: 'Commercial lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def sort_column
      CommercialLead.column_names.include?(params[:sort]) ? params[:sort] : "initial_contact"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_commercial_lead
      @commercial_lead = CommercialLead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commercial_lead_params
      params.require(:commercial_lead).permit(:first_name, :last_name, :email, :phone, :contact_type, :description, :source_id, :contact_date, :properties_referenced, :use, :notes, :properties_suggested, :properties_shown, :appointment_date, :company_name, :website, :size, :occupancy_date, :budget_max, :next_follow_up, :follow_up, :old_status, :old_broker, :old_source, :initial_contact, :initial_response, :broker_id, :status_id, :contact_method_id, :size_min, :size_max, :use_type_id, unit_ids: [], unit_reference_attributes: [:id], suggested_unit_attributes: [:id])
    end
end

app/helpers/commercial_leads_helper.rb
module CommercialLeadsHelper
end

app/views/commercial_leads/edit.html.erb
<div class="container">
  <h1>Editing Commercial Lead</h1>

  <div>
    <%= link_to 'Show', @commercial_lead %> |
    <%= link_to 'Back', commercial_leads_path %>
  </div>
  <br>
  <%= render 'form' %>
  <br>
  <%= link_to 'Show', @commercial_lead %> |
  <%= link_to 'Back', commercial_leads_path %>

</div>

app/views/commercial_leads/index.html.erb
<div class="container-fluid">
    <h1>Commercial Leads</h1>

<div class="row">
  <div class="col-md-4">
  <%= form_tag search_commercial_leads_path, method: :get, role: "search" do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
  <% end %>
  </div>
  
  <div class="col-md-5">
    
  <!-- Single button -->

    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Status <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Active", active_commercial_leads_path %></li>
        <li><%= link_to "Application/Proposal", application_commercial_leads_path %></li>
        <li><%= link_to "Signed", signed_commercial_leads_path %></li>
        <li><%= link_to "Rented Elsewhere", rented_elsewhere_commercial_leads_path %></li>
        <li><%= link_to "Not a Good Fit", not_a_good_fit_commercial_leads_path %></li>
        <li><%= link_to "Denied", denied_commercial_leads_path %></li>
        <li><%= link_to "Closed", closed_commercial_leads_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Source <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Craigslist", commercial_leads_path(:source_id => "2") %></li>
        <li><%= link_to "LoopNet", commercial_leads_path(:source_id => "3") %></li>
        <li><%= link_to "CityFeet", commercial_leads_path(:source_id => "9") %></li>
        <li><%= link_to "Referral", commercial_leads_path(:source_id => "5") %></li>
        <li><%= link_to "Broker", commercial_leads_path(:source_id => "4") %></li>
        <li><%= link_to "CoStar", commercial_leads_path(:source_id => "7") %></li>
        <li><%= link_to "Current/Past Tenant", commercial_leads_path(:source_id=> "8") %></li>
        <li><%= link_to "Unknown", commercial_leads_path(:source_id => "1") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>

    
    
  </div>
  <div class="col-md-3">
    <p>
    Download: 
    <%= link_to "CSV", commercial_leads_path(format: "csv") %> |
    <%= link_to "Excel", commercial_leads_path(format: "xls") %>
  </p>
  </div>  
</div>
  <br>

  <%= link_to new_commercial_lead_path, class: "btn btn-success" do %>
    <span class="glyphicon glyphicon-plus"></span> New Commercial Lead
  <% end %>

  <br>
  <br>
  

<!--    <h1>Commercial Leads</h1>

    <%= content_tag :div, "", id: "commercial_leads_chart", data: {commercial_leads: @commercial_leads} %>
    <br>
    <br>
    <br>
    <hr> -->

<table class="table table-hover">
    <thead>
      <tr>
        <th><%= sortable "initial_contact" %></th>
        <th><%= sortable "status" %></th>
        <th><%= sortable "first_name", "Name" %></th>
        <th><%= sortable "broker" %></th>
        <th><%= sortable "use_type" %></th>
        <th><%= sortable "use" %></th>
        <th><%= sortable "size_min", "Size" %></th>
        <th><%= sortable "occupancy_date" %></th>    
        <th><%= sortable "source" %></th>  
        <th><%= sortable "notes" %></th>
        <th><%= sortable "notes", "Contact Method" %></th>
        <th><%= sortable "appointment_date" %></th>
        <th><%= sortable "next_follow_up", "Next Follow Up" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @commercial_leads.each do |commercial_lead| %>
        <tr>
          <td><% if commercial_lead.initial_contact.present? %><%= commercial_lead.initial_contact.try(:strftime, "%A, %b %d, %Y") %><% end %></td>
          <td><% if commercial_lead.status.present? %><%= commercial_lead.status.name %><% end %></td>
          <td><% if commercial_lead.company_name.present? %><%= link_to commercial_lead.company_name, commercial_lead %><% end %><br>
              <%= link_to "#{commercial_lead.first_name} #{commercial_lead.last_name}", commercial_lead %></td>
          <td><% if commercial_lead.broker.present? %><%= link_to "#{commercial_lead.broker.first_name} #{commercial_lead.broker.last_name}", commercial_lead.broker %><% end %></td>
          <td><% if commercial_lead.use_type.present? %><%= commercial_lead.use_type.name %><% end %></td>
          <td><%= commercial_lead.use %></td>
          <td><%= commercial_lead.size_min %> - <%= commercial_lead.size_max %></td>
          <td><%= commercial_lead.occupancy_date.try(:strftime, "%m/%d/%Y") %></td>
          <td><% if commercial_lead.source.present? %><%= commercial_lead.source.name %><% end %></td>  
          <td>
            <% if commercial_lead.notes.length > 50 %>
              <%= truncate(commercial_lead.notes, length: 50) %>
              <%= link_to '...read more', '', class: "read-more-#{commercial_lead.id}" %>
              <script>
                $('.read-more-<%= commercial_lead.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript commercial_lead.notes %>')
                })
              </script>
            <% else %>
              <%= commercial_lead.notes %>
            <% end %>
          <td><% if commercial_lead.contact_method.present? %><%= commercial_lead.contact_method.name %><% end %></td>
          <td class="info"><%= commercial_lead.appointment_date.try(:strftime, "%m/%d/%Y") %></td>
          <td class="danger"><%= commercial_lead.next_follow_up.try(:strftime, "%m/%d/%Y") %></td>
          <td><%= link_to 'Edit', edit_commercial_lead_path(commercial_lead) %></td>
          <td><%= link_to 'Delete', commercial_lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>

    

  
</div>

app/views/commercial_leads/index_commercial_leads_old_with_sortable.html.erb
<div class="container">
    <h1>Commercial Leads</h1>

<div class="row">
  <div class="col-md-4">
  <%= form_tag search_commercial_leads_path, method: :get, role: "search" do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
  <% end %>
  <%= link_to "Show All", commercial_leads_path, class: "btn btn-default" %><br><br>
  </div>
  
  <div class="col-md-5">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Active Leads <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Active", commercial_leads_path(:follow_up => "true") %></li>
        <li><%= link_to "Inactive", commercial_leads_path(:follow_up => "false") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>
  <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Source <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Craigslist", commercial_leads_path(:source => "Craigslist") %></li>
        <li><%= link_to "LoopNet", commercial_leads_path(:source => "LoopNet") %></li>
        <li><%= link_to "CityFeet", commercial_leads_path(:source => "CityFeet") %></li>
        <li><%= link_to "Referral", commercial_leads_path(:source => "Referral") %></li>
        <li><%= link_to "Broker", commercial_leads_path(:source => "Broker") %></li>
        <li><%= link_to "CoStar", commercial_leads_path(:source => "CoStar") %></li>
        <li><%= link_to "Current/Past Tenant", commercial_leads_path(:source => "Current/Past Tenant") %></li>
        <li><%= link_to "Unknown", commercial_leads_path(:source => "") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>

    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Status <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Current", commercial_leads_path(:status => "Current") %></li>
        <li><%= link_to "Waiting", commercial_leads_path(:status => "Waiting") %></li>
        <li><%= link_to "Application", commercial_leads_path(:status => "Application") %></li>
        <li><%= link_to "Signed", commercial_leads_path(:status => "Signed") %></li>
        <li><%= link_to "Not a Good Fit", commercial_leads_path(:status => "Not a Good Fit") %></li>
        <li><%= link_to "Rented Elsewhere", commercial_leads_path(:status => "Elsewhere") %></li>
        <li><%= link_to "No Options", commercial_leads_path(:status => "No Options") %></li>
        <li><%= link_to "Unknown", commercial_leads_path(:status => "") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>
    
  </div>
  <div class="col-md-3">
    <p>
    Download: 
    <%= link_to "CSV", commercial_leads_path(format: "csv") %> |
    <%= link_to "Excel", commercial_leads_path(format: "xls") %>
  </p>
  </div>  
</div>
  <br>

  <%= link_to new_commercial_lead_path, class: "btn btn-success" do %>
    <span class="glyphicon glyphicon-plus"></span> New Commercial Lead
  <% end %>

  <br>
  <br>
  

<!--    <h1>Commercial Leads</h1>

    <%= content_tag :div, "", id: "commercial_leads_chart", data: {commercial_leads: @commercial_leads} %>
    <br>
    <br>
    <br>
    <hr> -->

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Contact Date</th>
        <th>Last Updated</th>
        <th>Status</th>
        <th>Active ?</th>
        <th>Name</th>
        <th>Broker</th>
        <th>Use</th>
        <th>Description</th>
        <th>Source</th>

        <th><%= sortable "updated_at" %></th>
        <th><%= sortable "status" %></th>
        <th><%= sortable "active" %></th>
        <th><%= sortable "first_name", "Name" %></th>
        <th><%= sortable "broker" %></th>
        <th><%= sortable "use" %></th>
        <th><%= sortable "description" %></th>
        <th><%= sortable "properties_referenced" %></th>
        <th><%= sortable "properties_suggested" %></th>
        <th><%= sortable "appointment_date" %></th>
        <th><%= sortable "properties_shown" %></th>
        <th><%= sortable "source" %></th>
        <th><%= sortable "notes" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @commercial_leads.each do |commercial_lead| %>
        <tr>
          <td><%= commercial_lead.contact_date.strftime("%m/%d/%Y") %></td>
           <td><%= commercial_lead.updated_at.strftime("%m/%d/%Y") %></td>
          <td><%= commercial_lead.status %></td>
          <td><%= commercial_lead.follow_up %></td>
          <td><%= link_to "#{commercial_lead.first_name} #{commercial_lead.last_name}", commercial_lead %></td>
          <td><%= commercial_lead.broker %></td>
          <td><%= commercial_lead.use %></td>
          <td>
            <% if commercial_lead.description.length > 50 %>
              <%= truncate(commercial_lead.description, length: 50) %>
              <%= link_to '...read more', '', class: "read-more-#{commercial_lead.id}" %>
              <script>
                $('.read-more-<%= commercial_lead.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript commercial_lead.description %>')
                })
              </script>
            <% else %>
              <%= commercial_lead.description %>
            <% end %>
          </td>
          <td><%= commercial_lead.properties_referenced %></td>
          <td><%= commercial_lead.properties_suggested %></td>
          <td class="info"><%= commercial_lead.appointment_date.try(:strftime, "%m/%d/%Y") %></td>
          <td class="info"><%= commercial_lead.properties_shown %></td>
          <td><%= commercial_lead.source %></td>
          <td>
            <% if commercial_lead.notes.length > 50 %>
              <%= truncate(commercial_lead.notes, length: 50) %>
              <%= link_to '...read more', '', class: "read-more-#{commercial_lead.id}" %>
              <script>
                $('.read-more-<%= commercial_lead.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript commercial_lead.notes %>')
                })
              </script>
            <% else %>
              <%= commercial_lead.notes %>
            <% end %>
          </td>
          
          <td><%= link_to 'Delete', commercial_lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>

  <br>

  
</div>

app/views/commercial_leads/new.html.erb
<div class="container">
  <h1>New Commercial Lead</h1>

  <%= render 'form' %>

  <%= link_to 'Back', commercial_leads_path %>

</div>

app/views/commercial_leads/search.html.erb
<div class="container-fluid">
    <h1>Commercial Leads</h1>

<div class="row">
  <div class="col-md-4">
  <%= form_tag search_commercial_leads_path, method: :get, role: "search" do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
  <% end %>
  </div>
  
  <div class="col-md-5">
    
  <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Status <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Current", commercial_leads_path(:status => "Current") %></li>
        <li><%= link_to "Waiting", commercial_leads_path(:status => "Waiting") %></li>
        <li><%= link_to "Application", commercial_leads_path(:status => "Application") %></li>
        <li><%= link_to "Signed", commercial_leads_path(:status => "Signed") %></li>
        <li><%= link_to "Not a Good Fit", commercial_leads_path(:status => "Not a Good Fit") %></li>
        <li><%= link_to "Rented Elsewhere", commercial_leads_path(:status => "Elsewhere") %></li>
        <li><%= link_to "No Options", commercial_leads_path(:status => "No Options") %></li>
        <li><%= link_to "Unknown", commercial_leads_path(:status => "") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Source <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Craigslist", commercial_leads_path(:source_id => "2") %></li>
        <li><%= link_to "LoopNet", commercial_leads_path(:source_id => "3") %></li>
        <li><%= link_to "CityFeet", commercial_leads_path(:source_id => "9") %></li>
        <li><%= link_to "Referral", commercial_leads_path(:source_id => "5") %></li>
        <li><%= link_to "Broker", commercial_leads_path(:source_id => "4") %></li>
        <li><%= link_to "CoStar", commercial_leads_path(:source_id => "7") %></li>
        <li><%= link_to "Current/Past Tenant", commercial_leads_path(:source_id=> "8") %></li>
        <li><%= link_to "Unknown", commercial_leads_path(:source_id => "1") %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "All Commercial Leads", commercial_leads_path %></li>
      </ul>
    </div>
    
  </div>
  <div class="col-md-3">
    <p>
    Download: 
    <%= link_to "CSV", commercial_leads_path(format: "csv") %> |
    <%= link_to "Excel", commercial_leads_path(format: "xls") %>
  </p>
  </div>  
</div>
  <br>

  <%= link_to new_commercial_lead_path, class: "btn btn-success" do %>
    <span class="glyphicon glyphicon-plus"></span> New Commercial Lead
  <% end %>

  <br>
  <br>
  

<!--    <h1>Commercial Leads</h1>

    <%= content_tag :div, "", id: "commercial_leads_chart", data: {commercial_leads: @commercial_leads} %>
    <br>
    <br>
    <br>
    <hr> -->

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sortable "initial_contact" %></th>
        <th><%= sortable "status" %></th>
        <th><%= sortable "first_name", "Name" %></th>
        <th><%= sortable "broker" %></th>
        <th><%= sortable "use_type" %></th>
        <th><%= sortable "use" %></th>
        <th><%= sortable "size_min", "Size" %></th>
        <th><%= sortable "occupancy_date" %></th>    
        <th><%= sortable "source" %></th>  
        <th><%= sortable "notes" %></th>
        <th><%= sortable "notes", "Contact Method" %></th>
        <th><%= sortable "appointment_date" %></th>
        <th><%= sortable "next_follow_up", "Next Follow Up" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @commercial_leads.each do |commercial_lead| %>
        <tr>
          <td><% if commercial_lead.initial_contact.present? %><%= commercial_lead.initial_contact.try(:strftime, "%A, %b %d, %Y") %><% end %></td>
          <td><% if commercial_lead.status.present? %><%= commercial_lead.status.name %><% end %></td>
          <td><%= link_to "#{commercial_lead.first_name} #{commercial_lead.last_name}", commercial_lead %></td>
          <td><% if commercial_lead.broker.present? %><%= link_to "#{commercial_lead.broker.first_name} #{commercial_lead.broker.last_name}", commercial_lead.broker %><% end %></td>
          <td><% if commercial_lead.use_type.present? %><%= commercial_lead.use_type.name %><% end %></td>
          <td><%= commercial_lead.use %></td>
          <td><%= commercial_lead.size_min %> - <%= commercial_lead.size_max %></td>
          <td><%= commercial_lead.occupancy_date.try(:strftime, "%m/%d/%Y") %></td>
          <td><% if commercial_lead.source.present? %><%= commercial_lead.source.name %><% end %></td>  
          <td>
            <% if commercial_lead.notes.length > 50 %>
              <%= truncate(commercial_lead.notes, length: 50) %>
              <%= link_to '...read more', '', class: "read-more-#{commercial_lead.id}" %>
              <script>
                $('.read-more-<%= commercial_lead.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript commercial_lead.notes %>')
                })
              </script>
            <% else %>
              <%= commercial_lead.notes %>
            <% end %>
          <td><% if commercial_lead.contact_method.present? %><%= commercial_lead.contact_method.name %><% end %></td>
          <td class="info"><%= commercial_lead.appointment_date.try(:strftime, "%m/%d/%Y") %></td>
          <td class="danger"><%= commercial_lead.next_follow_up.try(:strftime, "%m/%d/%Y") %></td>
          <td><%= link_to 'Edit', edit_commercial_lead_path(commercial_lead) %></td>
          <td><%= link_to 'Delete', commercial_lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>

  <br>

  
</div>