config/routes.rb
Rails.application.routes.draw do

  resources :use_types
  resources :contact_methods
  resources :statuses
  devise_for :users

  resources :properties do
    resources :units
  end
  resources :garages
  resources :sources
  resources :prequalifications
  resources :representations
  resources :residential_applications
  resources :units do
    collection do
      get 'search'
    end
  end
  resources :brokers do
    collection do
      get 'search'
    end
  end
  resources :residential_leads do
    collection do
      get 'search'
    end
    resources :residential_applications
    resources :prequalifications
  end
  
  get 'pages/home'
  get 'pages/available_units'

  resources :commercial_leads do
    collection do
      get 'search'
      get :active
      get :application
      get :signed
      get :rented_elsewhere
      get :not_a_good_fit
      get :denied
      get :closed
    end
  end

  root 'pages#home'

end

app/models/available_unit.rb
class AvailableUnit < ActiveRecord::Base

  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/broker.rb
class Broker < ActiveRecord::Base

  has_many :representations
  has_many :commercial_leads
  
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR company ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def broker_full_name
    "#{first_name} #{last_name}"
  end


  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |broker|
        csv << broker.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/commercial_lead.rb
class CommercialLead < ActiveRecord::Base

  has_many :unit_references
  has_many :units, :through => :unit_references
  has_many :suggested_units
  has_many :units, :through => :suggested_units
  belongs_to :source
  belongs_to :status
  belongs_to :contact_method
  belongs_to :broker
  belongs_to :use_type

  has_many :property
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR use ILIKE ? OR description ILIKE ? OR email ILIKE ? OR company_name ILIKE ? OR properties_referenced ILIKE ? OR properties_suggested ILIKE ? OR properties_shown ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |commercial_lead|
        csv << commercial_lead.attributes.values_at(*column_names)
      end
    end  
  end

end

app/models/contact_method.rb
class ContactMethod < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact_method|
        csv << contact_method.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/garage.rb
class Garage < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/prequalification.rb
class Prequalification < ActiveRecord::Base
  belongs_to :residential_lead
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :units
end

app/models/representation.rb
class Representation < ActiveRecord::Base
  belongs_to :brokers
  belongs_to :commercial_leads
end

app/models/residential_lead.rb
class ResidentialLead < ActiveRecord::Base

def self.search(search)
  where("first_name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
 
end

  has_many :prequalifications

  accepts_nested_attributes_for :prequalifications

  has_many :residential_applications

  accepts_nested_attributes_for :residential_applications

end

app/models/shown_unit.rb
class ShownUnit < ActiveRecord::Base
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |source|
        csv << source.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |status|
        csv << status.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/suggested_unit.rb
class SuggestedUnit < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :unit_references
  has_many :commercial_leads, :through => :unit_references
  has_many :suggested_units
  has_many :commercial_leads, :through => :suggested_units
  belongs_to :property


  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/unit_reference.rb
class UnitReference < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/use_type.rb
class UseType < ActiveRecord::Base
  has_many :commercial_leads
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all.order('property_code DESC')
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    @property_units = @property.units.order('available DESC', 'unit_number ASC')
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :address, :description, :short_description, :medium_description, :property_code, :notes)
    end
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_code %><br>
    <%= f.text_field :property_code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :medium_description %><br>
    <%= f.text_area :medium_description %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="container">  
  <h1>Editing Property</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @property %> |
  <%= link_to 'Back', properties_path %>
</div>

app/views/properties/index.html.erb
<div class="container">

  <h1>Listing Properties</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Property Code</th>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= link_to property.property_code, property %></td>
          <td><%= link_to property.name, property %></td>
          <td><%= property.address %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Property', new_property_path %>
</div>

app/views/properties/new.html.erb
<div class="container">
  <h1>New Property</h1>

  <%= render 'form' %>

  <%= link_to 'Back', properties_path %>
</div>

app/views/properties/show.html.erb
<div class="container">
  <h2>
    <%= @property.name %>
  </h2>
  <p>
    <strong>Property Code:</strong>
    <%= @property.property_code %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @property.address %>
  </p>

  <p>
    <strong>Short Description:</strong>
    <%= markdown@property.short_description %>
  </p>
   <p>
    <strong>Medium Description:</strong>
    <%= markdown@property.medium_description %>
  </p>

  <p>
    <strong>Long Description:</strong>
    <%= markdown@property.description %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= markdown@property.notes %>
  </p>

<h3>Available Units</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Unit Number</th>
      <th>Square Footage</th>
      <th>Lease Type</th>
      <th>Availability</th>
      <th>Monthly Rent</th>
      <th>Per SF Rent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_units.each do |unit| %>
      <tr>
        <td><%= link_to unit.unit_number, unit %></td>
        <td><%= number_with_delimiter(unit.sq_ft) %></td>
        <td><%= unit.lease_type %></td>
        <td><%= human_boolean(unit.available) %></td>
        <td><% if unit.market_rent.present? %>$<%= unit.market_rent %><% end %></td>
        <td><% if unit.net_rent_min.present? %>$<%= unit.net_rent_min %> - $<%= unit.net_rent_max %><% end %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
      </tr>
    <% end %>
   </tbody>
  </table>
 <br>
 <br>

 <%= link_to "Add New Unit", new_unit_path(property_id: @property), class: "btn btn-warning" %><br><br>

  <%= link_to 'Edit', edit_property_path(@property) %> |
  <%= link_to 'Back', properties_path %>
</div>