config/routes.rb
Rails.application.routes.draw do

  resources :use_types
  resources :contact_methods
  resources :statuses
  devise_for :users

  resources :properties do
    resources :units
  end
  resources :garages
  resources :sources
  resources :prequalifications
  resources :representations
  resources :residential_applications
  resources :units do
    collection do
      get 'search'
    end
  end
  resources :brokers do
    collection do
      get 'search'
    end
  end
  resources :residential_leads do
    collection do
      get 'search'
    end
    resources :residential_applications
    resources :prequalifications
  end
  
  get 'pages/home'
  get 'pages/available_units'

  resources :commercial_leads do
    collection do
      get 'search'
      get :active
      get :application
      get :signed
      get :rented_elsewhere
      get :not_a_good_fit
      get :denied
      get :closed
    end
  end

  root 'pages#home'

end

app/models/available_unit.rb
class AvailableUnit < ActiveRecord::Base

  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/broker.rb
class Broker < ActiveRecord::Base

  has_many :representations
  has_many :commercial_leads
  
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR company ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def broker_full_name
    "#{first_name} #{last_name}"
  end


  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |broker|
        csv << broker.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/commercial_lead.rb
class CommercialLead < ActiveRecord::Base

  has_many :unit_references
  has_many :units, :through => :unit_references
  has_many :suggested_units
  has_many :units, :through => :suggested_units
  belongs_to :source
  belongs_to :status
  belongs_to :contact_method
  belongs_to :broker
  belongs_to :use_type

  has_many :property
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR use ILIKE ? OR description ILIKE ? OR email ILIKE ? OR company_name ILIKE ? OR properties_referenced ILIKE ? OR properties_suggested ILIKE ? OR properties_shown ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |commercial_lead|
        csv << commercial_lead.attributes.values_at(*column_names)
      end
    end  
  end

end

app/models/contact_method.rb
class ContactMethod < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact_method|
        csv << contact_method.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/garage.rb
class Garage < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/prequalification.rb
class Prequalification < ActiveRecord::Base
  belongs_to :residential_lead
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :units
end

app/models/representation.rb
class Representation < ActiveRecord::Base
  belongs_to :brokers
  belongs_to :commercial_leads
end

app/models/shown_unit.rb
class ShownUnit < ActiveRecord::Base
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |source|
        csv << source.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |status|
        csv << status.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/suggested_unit.rb
class SuggestedUnit < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :unit_references
  has_many :commercial_leads, :through => :unit_references
  has_many :suggested_units
  has_many :commercial_leads, :through => :suggested_units
  belongs_to :property


  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/unit_reference.rb
class UnitReference < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/use_type.rb
class UseType < ActiveRecord::Base
  has_many :commercial_leads
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CRM", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Commercial Leads<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Active", active_commercial_leads_path %></li>
            <li><%= link_to "Application", application_commercial_leads_path %></li>
            <li><%= link_to "Signed", signed_commercial_leads_path %></li>
            <li><%= link_to "Rented Elsewhere", rented_elsewhere_commercial_leads_path %></li>
            <li><%= link_to "Not a Good Fit", not_a_good_fit_commercial_leads_path %></li>
            <li><%= link_to "Denied", denied_commercial_leads_path %></li>
            <li><%= link_to "Closed", closed_commercial_leads_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "All", commercial_leads_path %></li>
          </ul>
        </li>
        <li><%= link_to "Brokers", brokers_path %></li>
        <li><%= link_to "Properties", properties_path %></li>
        <li><%= link_to "Available Units", pages_available_units_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li> 
        <% end %>
      </ul>
      
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>