config/routes.rb
Rails.application.routes.draw do

  resources :use_types
  resources :contact_methods
  resources :statuses
  devise_for :users

  resources :properties do
    resources :units
  end
  resources :garages
  resources :sources
  resources :prequalifications
  resources :representations
  resources :residential_applications
  resources :units do
    collection do
      get 'search'
    end
  end
  resources :brokers do
    collection do
      get 'search'
    end
  end
  resources :residential_leads do
    collection do
      get 'search'
    end
    resources :residential_applications
    resources :prequalifications
  end
  
  get 'pages/home'
  get 'pages/available_units'

  resources :commercial_leads do
    collection do
      get 'search'
      get :active
      get :application
      get :signed
      get :rented_elsewhere
      get :not_a_good_fit
      get :denied
      get :closed
    end
  end

  root 'pages#home'

end

app/models/available_unit.rb
class AvailableUnit < ActiveRecord::Base

  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/broker.rb
class Broker < ActiveRecord::Base

  has_many :representations
  has_many :commercial_leads
  
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR company ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def broker_full_name
    "#{first_name} #{last_name}"
  end


  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |broker|
        csv << broker.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/commercial_lead.rb
class CommercialLead < ActiveRecord::Base

  has_many :unit_references
  has_many :units, :through => :unit_references
  has_many :suggested_units
  has_many :units, :through => :suggested_units
  belongs_to :source
  belongs_to :status
  belongs_to :contact_method
  belongs_to :broker
  belongs_to :use_type

  has_many :property
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR use ILIKE ? OR description ILIKE ? OR email ILIKE ? OR company_name ILIKE ? OR properties_referenced ILIKE ? OR properties_suggested ILIKE ? OR properties_shown ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
 
  end

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |commercial_lead|
        csv << commercial_lead.attributes.values_at(*column_names)
      end
    end  
  end

end

app/models/contact_method.rb
class ContactMethod < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact_method|
        csv << contact_method.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/garage.rb
class Garage < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/prequalification.rb
class Prequalification < ActiveRecord::Base
  belongs_to :residential_lead
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :units
end

app/models/representation.rb
class Representation < ActiveRecord::Base
  belongs_to :brokers
  belongs_to :commercial_leads
end

app/models/residential_lead.rb
class ResidentialLead < ActiveRecord::Base

def self.search(search)
  where("first_name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
 
end

  has_many :prequalifications

  accepts_nested_attributes_for :prequalifications

  has_many :residential_applications

  accepts_nested_attributes_for :residential_applications

end

app/models/shown_unit.rb
class ShownUnit < ActiveRecord::Base
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |source|
        csv << source.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :commercial_leads

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |status|
        csv << status.attributes.values_at(*column_names)
      end
    end  
  end
end

app/models/suggested_unit.rb
class SuggestedUnit < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :unit_references
  has_many :commercial_leads, :through => :unit_references
  has_many :suggested_units
  has_many :commercial_leads, :through => :suggested_units
  belongs_to :property


  def self.search(search)
    where("prospects ILIKE ?", "%#{search}%")
 
  end
end

app/models/unit_reference.rb
class UnitReference < ActiveRecord::Base
  belongs_to :unit
  belongs_to :commercial_lead
end

app/models/use_type.rb
class UseType < ActiveRecord::Base
  has_many :commercial_leads
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /available_units
  # GET /available_units.json
  def search
    if params[:search].present?
        @units = Unit.search(params[:search])
    else
        @units = Unit.all.order('lease_end_date DESC')
    end
  end

  def index
    @units = Unit.includes(:property).order('properties.name DESC, unit_number ASC')
  end

  # GET /available_units/1.json
  # GET /available_units/1
  def show
  end

  # GET /available_units/new
  def new
    @unit = Unit.new(property_id: params[:property_id])
  end

  # GET /available_units/1/edit
  def edit
  end

  # POST /available_units
  # POST /available_units.json
  def create
    @unit = Unit.new(unit_params, params[:property_id])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_units/1
  # PATCH/PUT /available_units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_units/1
  # DELETE /available_units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:unit_number, :sq_ft, :market_rent, :bedroom, :bathroom, :laundry, :address, :city, :zip, :craigslist_title, :short_description, :features, :lease_end_date, :prospects, :available, :property_id, :net_rent_min, :net_rent_max, :lease_type, unit_reference_attributes: [:id])
    end
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.collection_select(:property_id, Property.all, :id, :name, {:include_blank => true} )%>

  <div class="field">
    <%= f.label :unit_number %><br>
    <%= f.text_field :unit_number %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :sq_ft %><br>
    <%= f.text_field :sq_ft %>
  </div>
  <div class="field">
    <%= f.label :lease_type %><br>
    <%= f.select :lease_type, options_for_select([ "Gross", "NNN" ], "Gross") %>
  </div>
  <div class="field">
    <%= f.label :market_rent, "Monthly rent" %><br>
    <%= f.text_field :market_rent %>
  </div>
  <div class="field">
    <%= f.label :net_rent_min, "Rent per SF min" %><br>
    <%= f.text_field :net_rent_min %>
  </div>
  <div class="field">
    <%= f.label :net_rent_max, "Rent per SF max" %><br>
    <%= f.text_field :net_rent_max %>
  </div>
  <div class="field">
    <%= f.label :laundry %><br>
    <%= f.text_field :laundry %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_area :features %>
  </div>
   <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.text_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.text_field :bathroom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/available_units.html.erb
<div class="container">

<%= form_tag search_units_path, method: :get, role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>

<h1>Available Units</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Unit</th>
        <th>Property</th>
        <th>SQ FT</th>
        <th>Market Rent</th>
        <th>Availability</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @available_units.each do |unit| %>
        <tr>
          <td><%= link_to unit.unit_number, unit %></td>
          <td><%=link_to unit.property.try(:name), unit.property %></td>
          <td><%= number_with_delimiter(unit.sq_ft) %></td>
          <td>$<%= unit.market_rent %></td>
          <td><%= human_boolean(unit.available) %></td>
          
          <td><%= link_to 'Delete', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>


<br>

</div>

app/views/units/edit.html.erb
<div class="container">

<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

</div>

app/views/units/index.html.erb
<div class="container">

<%= link_to 'New Unit', new_unit_path %>

<%= form_tag search_units_path, method: :get, role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>

<h1>Units</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Unit</th>
        <th>Property</th>
        <th>SQ FT</th>
        <th>Market Rent</th>
        <th>Available</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @units.each do |unit| %>
        <tr>
          <td><%= link_to unit.unit_number, unit %></td>
          <td><%=link_to unit.property.try(:name), unit.property %></td>
          <td><%= number_with_delimiter(unit.sq_ft) %></td>
          <td>$<%= unit.market_rent %></td>
          <td><%= human_boolean(unit.available) %></td>
          <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
          <td><%= link_to 'Delete', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Unit', new_unit_path %>

</div>

app/views/units/new.html.erb
<div class="container">

  <h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

</div>

app/views/units/search.html.erb
<div class="container">

<%= link_to 'New Unit', new_unit_path %>

<%= form_tag search_units_path, method: :get, role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>

 <%= link_to "All Units", units_path %>

<h1>Units <small>Search results</small></h1>


  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sortable "unit_number", "Unit" %></th>
        <th><%= sortable "sq_ft" %></th>
        <th><%= sortable "market_rent" %></th>
        <th><%= sortable "available" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @units.each do |unit| %>
        <tr>
          <td><%= link_to unit.unit_number, unit %></td>
          <td><%= unit.sq_ft %></td>
          <td>$<%= unit.market_rent %></td>
          <td><%= unit.available %></td>
          
          <td><%= link_to 'Delete', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Unit', new_unit_path %>

</div>

app/views/units/show.html.erb
<div class="container">

  <p>
    <h1><% if @unit.property.present? %><%= @unit.property.name %><% else %> No Property Yet<% end %> - <%= @unit.unit_number %></h1>
  </p>

  <p>
  <strong>Available:</strong>
  <%= human_boolean@unit.available %>
  </p>
  
  <p><strong>Square Footage:</strong>
    <%= number_with_delimiter(@unit.sq_ft) %>
  </p>

  <p><strong>Lease Type:</strong> 
    <%= @unit.lease_type %>
  </p>

  <p><strong>Monthly Rent:</strong> 
    $<%= @unit.market_rent %>
  </p>

  <p><strong>Rent per SF:</strong> 
    $<%= @unit.net_rent_min %> - $<%= @unit.net_rent_max %>
  </p>

  <p><strong><%= @unit.bedroom %> bedroom | 
    <%= @unit.bathroom %> bath</strong>
  </p>

  <p>
    <strong>Laundry:</strong>
    <%= @unit.laundry %>
  </p>

  <p>
    <strong><u>About</u></strong>
    <%= markdown(@unit.short_description) %>
  </p>

  <p>
    <strong><u>Features</u></strong>
    <%= markdown(@unit.features) %>
  </p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'All Units', units_path %>
</div>